server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/soika
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

auth:
  service:
    url: http://localhost:8080

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    com.soika.chat: DEBUG

minio:
  endpoint: http://localhost:9000 #change to minio host
  accessKey: minioadmin
  secretKey: minioadmin
  bucket: avatars 